version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/" # Look for NuGet packages in the root directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 